
#
# This LookML file was generated by AtScale on 2024-06-05T17:55:59.275917375Z
#
# AtScale version: C2024.1.0
# Catalog: Sales Insights - BigQuery_develop2211

connection: "Connection 3"
label: "Sales Insights - BigQuery_develop2211"


include: "/views/Sales_Insights_-_BigQuery__develop2211/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

