
#
# This LookML file was generated by AtScale on 2024-06-05T17:42:35.742357503Z
#
# AtScale version: C2024.1.0
# Catalog: Sales Insights - 3123BigQuery_develop

connection: "Connection 3"
label: "Sales Insights - 3123BigQuery_develop"


include: "/views/Sales_Insights_-_3123BigQuery__develop/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

